# This version spins up the production version of the reporting service with a corresponding DB
# This is useful for circle ci testing, or for testing in conjuction with the other protocol services
#
version: '3.5'

networks:
  agency-network:
    name: agency-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  protocol-services-support:
    build:
      context: ./
      dockerfile: Dockerfile.production
    image: protocol-services-support
    container_name: protocol-services-support
    working_dir: /www
    ports:
      - "3023:3023"
    expose:
      - "3023"
    networks:
      - agency-network
    tty: true
    env_file:
      - ./.env

